### ISSUE TITLE
Generalise src CMakeLists.txt for building multiple libs

### ISSUE THREAD

**Issue by andrewcoughtrie** [MetOffice/Vernier#14]
Currently only a single library file will be created for all source, it would be best to have the ability to create multiple lib files if needed.

**Comment by hiker** [comment]
@andrewcoughtrie , I am confused. I get three different libs (f, c, c++)
```
.../local/lib$ ls -l
total 2008
drwxr-xr-x 3 joerg joerg    4096 Dec  9 13:08 cmake
lrwxrwxrwx 1 joerg joerg      15 Dec  9 13:08 libvernier.so -> libvernier.so.0
lrwxrwxrwx 1 joerg joerg      19 Dec  9 13:08 libvernier.so.0 -> libvernier.so.0.1.0
-rw-r--r-- 1 joerg joerg 1800088 Dec  9 13:08 libvernier.so.0.1.0
lrwxrwxrwx 1 joerg joerg      17 Dec  9 13:08 libvernier_c.so -> libvernier_c.so.0
lrwxrwxrwx 1 joerg joerg      21 Dec  9 13:08 libvernier_c.so.0 -> libvernier_c.so.0.1.0
-rw-r--r-- 1 joerg joerg  226048 Dec  9 13:08 libvernier_c.so.0.1.0
lrwxrwxrwx 1 joerg joerg      17 Dec  9 13:08 libvernier_f.so -> libvernier_f.so.0
lrwxrwxrwx 1 joerg joerg      21 Dec  9 13:08 libvernier_f.so.0 -> libvernier_f.so.0.1.0
-rw-r--r-- 1 joerg joerg   18408 Dec  9 13:08 libvernier_f.so.0.1.0
```

I was just about to open a ticket that they should all be merged into a single library. It seems unnecessarily complicated to have to link with three libraries when using Fortran (I tried removing e.g. c, but they are indeed all required).

**Comment by andrewcoughtrie** [comment]
This issue was related to the possible need for multiple C++ libs not the wrappers for the different bindings, I'm going to close this issue as it isn't really needed at the moment and won't be done any time soon. 

The current system for the language bindings isn't really any more complicated than NetCDF but I can see it might be easier to have a single library. If you want to open an issue to merge them that's fine, the work won't be a priority at the moment due to other work but if you're happy to do it yourself I'll review it.
