### ISSUE TITLE
Create a mechanism for turning the profiler off

### ISSUE THREAD

**Issue by andrewcoughtrie** [MetOffice/Vernier#4]
Create a mechanism for turning the profiler off  (Useful to sort out early on, so that it doesn't become difficult to add later.) e.g. A `const` logical/boolean so that they are removed by optimising compilers.

Will need looking into, unsure exactly what the requirements are, @mo-mglover can you provide more detail.

**Comment by mo-mglover** [comment]
I'm going to close this one. I disagree with myself over the wisdom of building the logicals into Vernier.  Different client applications would have different needs.

Also, the `if` test is best done in the application, for reasons of compiler optimisations outlined above.
